
jobs:
  - name: runsh-job-pub1
    type: runSh
    allowPublicAccess: false
    
    steps:
      - IN: sample-pub
        showBuildStatus: true
     # - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-pub/gitRepo/echo.sh
    flags: job1
    
  - name: runcliscript-job-pub
    type: runCLI
    allowPublicAccess: true
    steps:      
      - IN: sample-pub
        showBuildStatus: false
      - TASK:
        - script: IN/sample-pub/gitRepo/echo.sh
    flags: runCli-public

        
        
  - name: manifest_dep
    type: manifest
    steps:
      - IN: sample_img_pub   
      
      
      
     # - IN: t1
